#!/bin/bash

echo "🔄 Restarting Backend Server to Load Segmentation Routes..."
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Go to the terminal running the backend server"
echo "2. Stop it with Ctrl+C"
echo "3. Restart with: npm start (or npm run dev)"
echo ""
echo "After restart, the segmentation routes will be available at:"
echo "  - GET  /api/segmentation/stats"
echo "  - GET  /api/segmentation/available-segments"
echo "  - POST /api/segmentation/filtered-customers"
echo "  - POST /api/segmentation/preview-count"
echo "  - POST /api/segmentation/customers-by-ids"
echo ""
echo "To verify routes are loaded, check the server logs for:"
echo "  'Server running on port 5001'"
echo ""
echo "Then test with:"
echo "  curl http://localhost:5001/api/segmentation/stats"
echo ""
